---

- name: Start
  hosts: localhost
  remote_user: testuser1
  gather_facts: false
  vars_files:
   - vars/info.yml

  task:
   - name: Create a VPC with default tenancy
     ec2_vpc_net: 
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       name: test_vpc_net
       cidr_block: 10.10.0.0/16
       tags: 
         module: ec2_vpc_net
       tenancy: default
     register:ansibleVPC

   - name: vpc output
     debug:
       var: ansibleVPC

   - name: create internet gw for ansible vpc
     ec2_vpc_igw:
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key}}"
       region: "{{ aws_region }}"
       state: present
       vpc_id: "{{ ansibleVPC.vpc.id }}"
       tags:
         Name: ansibleVPC_IGW
     register: ansibleVPC_igw

   - name: display ansibleVPC IGW details
     debug: 
       var: ansibleVPC_igw

   - name: create public subnet in "{{ aws_region }}"
     ec2_vpc_subnet: 
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       state: present
       cidr: 10.10.0.0/16
       vpc_id: "{{ ansibleVPC.vpc.id }}"
       map_public: yes
       tags: 
         Name: public_subnet
     register: public_subnet

   - name: show public subnet details
     debug: 
       var: public_subnet

   - name: create new route table for public subnet
     ec2_vpc_route_table:
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       state: present
       vpc_id: "{{ ansibleVPC.vpc.id }}"
       tags: 
         Name: rt_ansibleVPC_PublicSubnet
       subnets: 
         - "{{ public_subnet.subnet.id }}"
       routes:
         - dest: 0.0.0.0/0
           gateway_id: "{{ ansibleVPC_igw.gateway_id }}"
     register: rt_ansibleVPC_PublicSubnet

   - name: display public route table
     debug: 
       var: rt_ansibleVPC_PublicSubnet
